name: 1.2.0$(Rev:.r)

trigger:
- master

resources:
- repo: self

variables:
  - group: demo
  - name: vmImageName
    value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd /home/vsts/work/1/s
          git submodule init
          git submodule update --remote --merge
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: $(containerRegistry)
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        repository: 'ikolomiyets/demo-frontend'
        tags: |
          $(Build.BuildNumber)
          latest
    - task: publish-artifact@1
      displayName: Publish artifact version in to the artifactz.io
      inputs:
        apiToken: $(artifactz.apiToken)
        stage: 'Development'
        flow: 'Standard'
        name: 'demo-frontend'
        type: 'DockerImage'
        version: $(Build.BuildNumber)
    - task: push-artifact@1
      inputs:
        apiToken: $(artifactz.apiToken)
        stage: 'Development'
        name: 'demo-frontend'
